- hosts: go
  gather_facts: no
  become: yes
  tasks:
    - name: Copy go binary to remote 
      copy:
        src: "{{ artifact }}"
        dest: "/home/guobin/hellogo"
        mode: '0644'
    - name: Stop running go
      command: pkill hellogo
      ignore_errors: yes
    - name: Start go
      command: 
        cmd: ./hellogo
        chdir: /home/guobin
